# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_Window(object):
    def setupUi(self, login_Window):
        login_Window.setObjectName("login_Window")
        login_Window.resize(686, 388)
        login_Window.setMaximumSize(QtCore.QSize(686, 388))
        login_Window.setAutoFillBackground(False)
        login_Window.setStyleSheet("background-color: rgba(242, 242, 138, 1);")
        self.centralwidget = QtWidgets.QWidget(login_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_openResource = QtWidgets.QPushButton(self.centralwidget)
        self.btn_openResource.setGeometry(QtCore.QRect(250, 200, 151, 51))
        self.btn_openResource.setObjectName("btn_openResource")
        self.btn_openResource.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        self.btn_regist = QtWidgets.QPushButton(self.centralwidget)
        self.btn_regist.setGeometry(QtCore.QRect(430, 290, 151, 51))
        self.btn_regist.setObjectName("btn_regist")
        self.btn_regist.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(50, 290, 151, 51))
        self.btn_open.setObjectName("btn_open")
        self.btn_open.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 80, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 140, 55, 16))
        self.label_2.setObjectName("label_2")
        self.txt_login = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_login.setGeometry(QtCore.QRect(130, 70, 451, 31))
        self.txt_login.setObjectName("txt_login")
        self.txt_login.setStyleSheet("background-color: white;border-width: 2px;border-color: black;")
        self.txt_password = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(130, 130, 451, 31))
        self.txt_password.setObjectName("txt_password")
        self.txt_password.setStyleSheet("background-color: white;border-width: 2px;border-color: black;")
        login_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_Window)
        QtCore.QMetaObject.connectSlotsByName(login_Window)

    def retranslateUi(self, login_Window):
        _translate = QtCore.QCoreApplication.translate
        login_Window.setWindowTitle(_translate("login_Window", "Авторизация"))
        self.btn_openResource.setText(_translate("login_Window", "Доступ к ресурсу"))
        self.btn_regist.setText(_translate("login_Window", "Регистрация"))
        self.btn_open.setText(_translate("login_Window", "Вход"))
        self.label.setText(_translate("login_Window", "Почта"))
        self.label_2.setText(_translate("login_Window", "Пароль"))
