# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 170)
        MainWindow.setMaximumSize(QtCore.QSize(403, 170))
        MainWindow.setStyleSheet("background-color: rgba(242, 242, 138, 1);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_edit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit.setGeometry(QtCore.QRect(25, 90, 150, 70))
        self.btn_edit.setObjectName("btn_edit")
        self.btn_edit.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        # self.btn_add_photo = QtWidgets.QPushButton(self.centralwidget)
        # self.btn_add_photo.setGeometry(QtCore.QRect(225, 40, 150, 71))
        # self.btn_add_photo.setObjectName("btn_add_photo")
        # self.btn_add_photo.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(225, 90, 150, 70))
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_cancel.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        self.btn_update = QtWidgets.QPushButton(self.centralwidget)
        self.btn_update.setGeometry(QtCore.QRect(300, 40, 75, 30))
        self.btn_update.setObjectName("btn_update")
        self.btn_update.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        self.pbar = QtWidgets.QProgressBar(self)
        self.pbar.setGeometry(QtCore.QRect(25, 40, 275, 30))
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 380, 20))
        self.label_1.setObjectName("label_1")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главная страница"))
        self.btn_edit.setText(_translate("MainWindow", "Редактировать \nданные"))
        # self.btn_add_photo.setText(_translate("MainWindow", "Добавить фото"))
        self.btn_cancel.setText(_translate("MainWindow", "Отмена"))
        self.btn_update.setText(_translate("MainWindow", "Обновить"))
        self.label_1.setText(_translate("MainWindow", "Статус готовности системы для распознания вашего лица"))
