# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 410)
        MainWindow.setMaximumSize(QtCore.QSize(800, 410))
        MainWindow.setStyleSheet("background-color: rgba(242, 242, 138, 1);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 60, 55, 16))
        self.label.setObjectName("label")
        self.txt_name = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name.setGeometry(QtCore.QRect(160, 50, 311, 31))
        self.txt_name.setObjectName("txt_name")
        self.txt_name.setStyleSheet("background-color: white;border-width: 2px;border-color: black;")
        self.txt_surname = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_surname.setGeometry(QtCore.QRect(160, 100, 311, 31))
        self.txt_surname.setObjectName("txt_surname")
        self.txt_surname.setStyleSheet("background-color: white;border-width: 2px;border-color: black;")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 55, 16))
        self.label_2.setObjectName("label_2")
        self.txt_login = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_login.setGeometry(QtCore.QRect(160, 150, 311, 31))
        self.txt_login.setObjectName("txt_login")
        self.txt_login.setStyleSheet("background-color: white;border-width: 2px;border-color: black;")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 55, 16))
        self.label_4.setObjectName("label_4")
        self.txt_password = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(160, 200, 311, 31))
        self.txt_password.setObjectName("txt_password")
        self.txt_password.setStyleSheet("background-color: white;border-width: 2px;border-color: black;")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 210, 55, 16))
        self.label_5.setObjectName("label_5")
        self.txt_mail = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_mail.setGeometry(QtCore.QRect(160, 250, 311, 31))
        self.txt_mail.setObjectName("txt_mail")
        self.txt_mail.setStyleSheet("background-color: white;border-width: 2px;border-color: black;")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 260, 55, 16))
        self.label_6.setObjectName("label_6")
        self.btn_add_photo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_photo.setGeometry(QtCore.QRect(570, 135, 161, 61))
        self.btn_add_photo.setObjectName("btn_add_photo")
        self.btn_add_photo.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(570, 330, 161, 61))
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_cancel.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(50, 330, 161, 61))
        self.btn_save.setObjectName("btn_save")
        self.btn_save.setStyleSheet("background-color: rgba(43, 199, 255, 1);border-width: 2px;border-color: black;")
        self.pbar = QtWidgets.QProgressBar(self)
        self.pbar.setGeometry(QtCore.QRect(520, 80, 280, 30))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Регистрация"))
        self.label.setText(_translate("MainWindow", "Имя"))
        self.label_2.setText(_translate("MainWindow", "Фамилия"))
        self.label_4.setText(_translate("MainWindow", "Логин"))
        self.label_5.setText(_translate("MainWindow", "Пароль"))
        self.label_6.setText(_translate("MainWindow", "Почта"))
        self.btn_add_photo.setText(_translate("MainWindow", "Добавить фото"))
        self.btn_cancel.setText(_translate("MainWindow", "Отмена"))
        self.btn_save.setText(_translate("MainWindow", "Сохранить"))
